#!/usr/bin/env bash
# This script shows  a list of currently running processes.
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# show process hierarchy

ps -a -x -u -f
